### ISSUE TITLE
404:  (https://confpad.github.io/data/conferences.json)

### ISSUE THREAD

**Issue by lex111** [confpad/confpad.github.io#8]
Location: https://confpad.github.io/

![image](https://user-images.githubusercontent.com/4408379/58387985-e45b2c80-8020-11e9-99f8-b535cc4f34b7.png)

**Comment by lex111** [comment]
cc @petasittek

**Comment by petasittek** [comment]
Thanks, @lex111! ConfPad is served via Netlify so I've just set custom domain for GitHub Pages to confpad.io to enforce a redirect.
